print ("Hello. I'm a pesel verification program. Please give me some information about you.")
Y = int(input("Enter a year of birth (last 2 digits) >>> "))
M = int(input("Enter a month of birth (as a number) >>> "))
D = int(input("Enter a day of birth (as a number) >>> "))
P = input("Enter a your gender on birth (male, female) >>> ")
list(yourpesel)
print = (yourpesel)